version: '3'
services:
  neo4j:
      image: neo4j:3.5.26
      container_name: neo4j_amundsen
      environment:
        - NEO4J_AUTH=neo4j/test
      ulimits:
        nofile:
          soft: 40000
          hard: 40000
      ports:
          - 7474:7474
          - 7687:7687
      volumes:
          - ./example/docker/neo4j/conf:/var/lib/neo4j/conf
          - ./.local/neo4j/data:/data
      networks:
        - amundsennet
  elasticsearch:
      image: elasticsearch:6.7.0
      container_name: es_amundsen
      ports:
          - 9200:9200
      networks:
        - amundsennet
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
  amundsensearch:
      build:
        context: .
        dockerfile: Dockerfile.search.public
      container_name: amundsensearch
      ports:
        - 5001:5001
      depends_on:
        - elasticsearch
      networks:
        - amundsennet
      environment:
        - PROXY_ENDPOINT=es_amundsen
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC
        # - FLASK_OIDC_WHITELISTED_ENDPOINTS=api.healthcheck
  amundsenmetadata:
      build:
        context: .
        dockerfile: Dockerfile.metadata.public
      container_name: amundsenmetadata
      depends_on:
        - neo4j
      ports:
        - 5002:5002
      networks:
        - amundsennet
      environment:
        - PROXY_HOST=bolt://neo4j_amundsen
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC

        # - FLASK_OIDC_REDIRECT_URI=/authorization-code/callback
  amundsenfrontend:
      build:
        args:
          SEARCHSERVICE_BASE: http://amundsensearch:5001
          METADATASERVICE_BASE: http://amundsenmetadata:5002
        context: .
        dockerfile: Dockerfile.frontend.local
      container_name: amundsenfrontend
      depends_on:
        - amundsenmetadata
        - amundsensearch
      ports:
        - 5000:5000
      networks:
        - amundsennet
      environment:
        - SEARCHSERVICE_BASE=http://amundsensearch:5001
        - METADATASERVICE_BASE=http://amundsenmetadata:5002
        - FLASK_APP_MODULE_NAME=flaskoidc
        - FLASK_APP_CLASS_NAME=FlaskOIDC
        # Only for easy config-less Quickstart bookmark evalutation. `TestConfig` extends ordinary `LocalConfig` by
        # defining `AUTH_USER_METHOD` to a hardcoded dummy user in `amundsen_application.tests.test_utils.get_test_user()`
        # See further docs in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/configuration.md#flask
        # and https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/configuration.md#authentication
        - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.oidc_config.OidcConfig
        - FLASK_OIDC_CONFIG_URL=https://accounts.google.com/.well-known/openid-configuration
        - FLASK_OIDC_REDIRECT_URI=/authorization-code/callback
      env_file:
        - .env

networks:
  amundsennet:


